# Generated by Django 6.0.4 on 2026-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Имя продукта')),
                ('type_product', models.CharField(choices=[('CL', 'Кулеры'), ('AR', 'Аксессуары'), ('WE', 'Вода'), ('B20L', 'Вода c тарой 20L'), ('BT', 'Тара')], default='CL', max_length=4, verbose_name='Тип продукта')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('track_inventory', models.BooleanField(default=True, help_text='Если отмечено, то для этого продукта будет вестись учет остатков на складе', verbose_name='Учитывать на складе')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
