# Generated by Django 5.1.6 on 2025-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Имя продукта')),
                ('type_product', models.CharField(choices=[('CL', 'Кулеры'), ('AR', 'Аксессуары'), ('W20L', 'Вода 20L'), ('W10L', 'Вода 10L'), ('W5L', 'Вода 5L'), ('B20L', 'Вода c тарой 20L')], default='CL', max_length=4, verbose_name='Тип продукта')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
