# Generated by Django 5.1.6 on 2025-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantitly',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
