# Generated by Django 5.1.6 on 2026-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('CL', 'Кулеры'), ('AR', 'Аксессуары'), ('19W', 'Вода'), ('B19W', 'Вода + тара 19'), ('BT', 'Тара')], default='CL', max_length=4, verbose_name='Тип продукта'),
        ),
    ]
