# Generated by Django 5.1.6 on 2026-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Если отмечено, то для этого продукта будет вестись учет остатков на складе', verbose_name='Учитывать на складе'),
        ),
    ]
