# Generated by Django 5.1.6 on 2025-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantitly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantitly',
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('CL', 'Кулеры'), ('AR', 'Аксессуары'), ('WE', 'Вода'), ('B20L', 'Вода c тарой 20L')], default='CL', max_length=4, verbose_name='Тип продукта'),
        ),
    ]
