# Generated by Django 5.1.6 on 2026-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='URL изображения для карточки товара в каталоге', verbose_name='Фото товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible_in_catalog',
            field=models.BooleanField(default=True, help_text='Если отмечено, товар показывается в каталоге клиентского приложения', verbose_name='Показывать в каталоге'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Если отмечено, то для этого товара будет учитываться учет остатков на складе', verbose_name='Учитывать на складе'),
        ),
    ]
