# Generated by Django 5.1.6 on 2025-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('CL', 'Кулеры'), ('AR', 'Аксессуары'), ('WE', 'Вода'), ('B20L', 'Вода c тарой 20L'), ('BT', 'Тара')], default='CL', max_length=4, verbose_name='Тип продукта'),
        ),
    ]
