# Generated by Django 5.1.6 on 2026-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url_product_is_visible_in_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара (будет доступно по /media/products/)', null=True, upload_to='products/', verbose_name='Фото товара (файл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Внешний URL изображения (если не загружен файл)', verbose_name='Фото товара (URL)'),
        ),
    ]
