# Generated by Django 6.0.4 on 2026-04-29 13:55

import apps.accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='Доход')),
                ('consumption', models.IntegerField(blank=True, default=0, null=True, verbose_name='Расход')),
                ('profit', models.IntegerField(blank=True, default=0, null=True, verbose_name='Прибыль')),
                ('card_profit', models.IntegerField(blank=True, default=0, null=True, verbose_name='Прибыль на карту')),
                ('date', models.DateField(verbose_name='Дата сводки')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('transaction_type', models.CharField(choices=[('PL', 'Доход'), ('MI', 'Расход')], max_length=2, verbose_name='Тип трансакции')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name=' Общая сумма')),
                ('card_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма картой')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('source', models.CharField(max_length=100, verbose_name='Источник операции')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата заключения')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.accounting.models.contract_upload_path, validators=[apps.accounting.models.validate_contract_file], verbose_name='Документ')),
                ('contract_type', models.CharField(choices=[('BY', 'В минус'), ('SL', 'В плюс')], max_length=2, verbose_name='Тип контрака')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма рассрочки')),
                ('paid_amount', models.IntegerField(blank=True, null=True, verbose_name='Оплаченно')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата след платежа')),
                ('status', models.CharField(choices=[('AC', 'Активный'), ('OV', 'Просроченый'), ('CL', 'Погашенный')], max_length=2, verbose_name='Статус рассрочки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма взноса')),
                ('payment_date', models.DateField(verbose_name='Дата взноса')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.installment')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment', models.DateField(blank=True, null=True, verbose_name='Дата последней выплаты')),
                ('balance', models.IntegerField(blank=True, default=0, verbose_name='Баланс')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workewrs', to='workers.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='Примечание')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('SA', 'Зарплата'), ('FI', 'Штраф'), ('BO', 'Бонус')], max_length=2, verbose_name='Тип платежа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.salary')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, verbose_name='Описание предмета')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contract')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
