# Generated by Django 5.1.6 on 2026-08-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('workers', '0004_alter_worker_worker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_orders_created_total', models.PositiveIntegerField(default=0, help_text='Общее количество заказов, созданных в старой системе до запуска WERP.', verbose_name='Заказов создано (история)')),
                ('historical_water_sold_total', models.PositiveIntegerField(default=0, help_text='Общее количество проданной основной воды (в штуках) в старой системе до запуска WERP.', verbose_name='Продано основной воды (история)')),
                ('werp_start_date', models.DateField(blank=True, help_text='Дата, с которой начат учёт в WERP. Используется для подписи «Включая данные до запуска WERP».', null=True, verbose_name='Дата запуска WERP')),
                ('source', models.CharField(blank=True, default='', help_text='Откуда взяты исторические данные (например, «Перенос из 1С, акт №...»)', max_length=255, verbose_name='Источник / комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_stats_created', to='workers.worker', verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_stats_updated', to='workers.worker', verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Историческая база (до WERP)',
                'verbose_name_plural': 'Историческая база (до WERP)',
                'constraints': [models.CheckConstraint(condition=models.Q(('historical_orders_created_total__gte', 0)), name='historical_orders_created_total_gte_0'), models.CheckConstraint(condition=models.Q(('historical_water_sold_total__gte', 0)), name='historical_water_sold_total_gte_0')],
            },
        ),
    ]
