# Generated by Django 5.1.6 on 2025-03-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_contract_client'),
        ('clients', '0004_rename_adress_client_address'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма рассрочки')),
                ('paid_amount', models.IntegerField(verbose_name='Оплаченно')),
                ('due_date', models.DateField(verbose_name='Дата след платежа')),
                ('status', models.CharField(choices=[('AC', 'Активный'), ('OV', 'Просроченый'), ('CL', 'Погашенный')], verbose_name='Статус рассрочки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма взноса')),
                ('payment_date', models.DateField(verbose_name='Дата взноса')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Платежи', to='accounting.installment')),
            ],
        ),
    ]
