# Generated by Django 5.1.6 on 2026-08-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_historical_stats'),
        ('products', '0002_alter_product_type_product'),
        ('warehouse', '0003_remove_stockbalance_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'Рассрочка', 'verbose_name_plural': 'Рассрочки'},
        ),
        migrations.RemoveField(
            model_name='installment',
            name='product',
        ),
        migrations.AddField(
            model_name='subjectcontract',
            name='warehouse_product',
            field=models.ForeignKey(blank=True, help_text='Для закупки комплектующих (пакеты, тара, крышки). Либо товар ассортимента, либо складской продукт.', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseproduct', verbose_name='Складской продукт (комплектующие)'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оплаченно'),
        ),
        migrations.CreateModel(
            name='InstallmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price_per_unit', models.IntegerField(blank=True, null=True, verbose_name='Цена за единицу')),
                ('subtotal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма позиции')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.installment', verbose_name='Рассрочка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция рассрочки',
                'verbose_name_plural': 'Позиции рассрочки',
            },
        ),
    ]
