# Generated by Django 5.1.6 on 2025-03-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_installment_paymentsinstallment'),
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='Примечание')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('SA', 'Зарплата'), ('FI', 'Штраф'), ('BO', 'Бонус')], verbose_name='Тип платежа')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment', models.DateField(verbose_name='Дата последней выплаты')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workewrs', to='workers.worker', verbose_name='Работник')),
            ],
        ),
    ]
