# Generated by Django 5.1.6 on 2026-08-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_installment_options_remove_installment_product_and_more'),
        ('logistics', '0008_order_display_number_and_counter'),
        ('workers', '0007_remove_dispatcher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Сотрудник/курьер, который оформил рассрочку. Для заказа подставляется автоматически.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_installments', to='workers.worker', verbose_name='Кто оформил'),
        ),
        migrations.AddField(
            model_name='installment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Если рассрочка оформлена по заказу — укажите заказ. Позиции подтянутся автоматически.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='logistics.order', verbose_name='Заказ'),
        ),
    ]
