# Generated by Django 5.1.6 on 2026-08-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_installment_issued_by_installment_order'),
        ('workers', '0008_worker_salary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='workers.worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_type',
            field=models.CharField(choices=[('SA', 'Зарплата'), ('AD', 'Аванс'), ('FI', 'Штраф'), ('BO', 'Бонус')], max_length=2, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.salary'),
        ),
        migrations.CreateModel(
            name='SalaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день расчётного месяца (например, 2026-08-01).', verbose_name='Месяц')),
                ('salary_amount', models.IntegerField(default=0, help_text='Фиксированный оклад, начисленный за этот месяц.', verbose_name='Оклад за месяц')),
                ('bonuses', models.IntegerField(default=0, verbose_name='Бонусы')),
                ('fines', models.IntegerField(default=0, verbose_name='Штрафы')),
                ('advances', models.IntegerField(default=0, verbose_name='Выдано авансов')),
                ('paid_salary', models.IntegerField(default=0, verbose_name='Выплачено зарплаты')),
                ('salary_date', models.DateField(blank=True, help_text='Дата, когда должна быть выплачена зарплата за этот месяц.', null=True, verbose_name='Дата зарплаты')),
                ('status', models.CharField(choices=[('OP', 'Открыт'), ('PD', 'Выплачен'), ('CL', 'Закрыт')], default='OP', max_length=2, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_periods', to='workers.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Зарплатный период',
                'verbose_name_plural': 'Зарплатные периоды',
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Зарплатный месяц, к которому относится платёж. Подставляется автоматически.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.salaryperiod', verbose_name='Период'),
        ),
        migrations.AddConstraint(
            model_name='salaryperiod',
            constraint=models.UniqueConstraint(fields=('worker', 'month'), name='unique_worker_month'),
        ),
    ]
