# Generated by Django 5.1.6 on 2025-03-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_salarypayment_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.salary', verbose_name='Зарплата рабоника'),
        ),
    ]
