# Generated by Django 5.1.6 on 2025-03-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_salarypayment_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.salary', verbose_name='Зарплата рабоника'),
        ),
    ]
