# Generated by Django 5.1.6 on 2026-08-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_salary_worker_alter_salarypayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-date'], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['-date'], 'verbose_name': 'Дневная сводка', 'verbose_name_plural': 'Дневные сводки'},
        ),
        migrations.AlterModelOptions(
            name='financialtransactions',
            options={'ordering': ['-date'], 'verbose_name': 'Финансовая транзакция', 'verbose_name_plural': 'Финансовые транзакции'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассрочка', 'verbose_name_plural': 'Рассрочки'},
        ),
        migrations.AlterModelOptions(
            name='paymentsinstallment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Платёж по рассрочке', 'verbose_name_plural': 'Платежи по рассрочкам'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Зарплата', 'verbose_name_plural': 'Зарплаты'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-date'], 'verbose_name': 'Платёж по зарплате', 'verbose_name_plural': 'Платежи по зарплате'},
        ),
        migrations.AlterModelOptions(
            name='subjectcontract',
            options={'verbose_name': 'Предмет контракта', 'verbose_name_plural': 'Предметы контракта'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('BY', 'В минус'), ('SL', 'В плюс')], max_length=2, verbose_name='Тип контракта'),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='transaction_type',
            field=models.CharField(choices=[('PL', 'Доход'), ('MI', 'Расход')], max_length=2, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='paymentsinstallment',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentsinstallment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.installment', verbose_name='Рассрочка'),
        ),
        migrations.AlterField(
            model_name='subjectcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contract', verbose_name='Контракт'),
        ),
    ]
