# Generated by Django 5.1.6 on 2025-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_salarypayment_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='last_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней выплаты'),
        ),
    ]
