# Generated by Django 5.1.6 on 2025-03-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_salary_balance_alter_salary_last_payment'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='Доход')),
                ('consumption', models.IntegerField(verbose_name='Расход')),
                ('profit', models.IntegerField(verbose_name='Расход')),
                ('date', models.DateField(verbose_name='Дата сводки')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('transaction_type', models.CharField(choices=[('PL', 'Доход'), ('MI', 'Расход')], verbose_name='Тип трансакции')),
                ('amount', models.CharField(verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('related_object', models.CharField(max_length=255, verbose_name='Источник операции')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, verbose_name='Описание предмета')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contract')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
