# Generated by Django 5.1.6 on 2025-03-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_finance_financialtransactions_subjectcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectcontract',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
