# Generated by Django 5.1.6 on 2025-04-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_rename_quantity_subjectcontract_quantitly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата след платежа'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оплаченно'),
        ),
        migrations.AlterField(
            model_name='paymentsinstallment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Платежи', to='accounting.installment'),
        ),
    ]
