# Generated by Django 5.1.6 on 2025-04-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransactions',
            name='card_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма картой'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='consumption',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' Общая сумма'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма рассрочки'),
        ),
        migrations.AlterField(
            model_name='paymentsinstallment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма взноса'),
        ),
        migrations.AlterField(
            model_name='paymentsinstallment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.installment'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='balance',
            field=models.IntegerField(blank=True, default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма'),
        ),
    ]
