# Generated by Django 5.1.6 on 2025-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_financialtransactions_card_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialtransactions',
            old_name='related_object',
            new_name='source',
        ),
        migrations.AddField(
            model_name='finance',
            name='card_profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Прибыль на карту'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Прибыль'),
        ),
    ]
