# Generated by Django 5.1.6 on 2025-04-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_rename_related_object_financialtransactions_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransactions',
            name='source',
            field=models.CharField(verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.salary'),
        ),
    ]
