# Generated by Django 5.1.6 on 2026-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_contract_client_alter_installment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('BY', 'В минус'), ('SL', 'В плюс')], max_length=2, verbose_name='Тип контрака'),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='financialtransactions',
            name='transaction_type',
            field=models.CharField(choices=[('PL', 'Доход'), ('MI', 'Расход')], max_length=2, verbose_name='Тип трансакции'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('AC', 'Активный'), ('OV', 'Просроченый'), ('CL', 'Погашенный')], max_length=2, verbose_name='Статус рассрочки'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_type',
            field=models.CharField(choices=[('SA', 'Зарплата'), ('FI', 'Штраф'), ('BO', 'Бонус')], max_length=2, verbose_name='Тип платежа'),
        ),
    ]
