# Generated by Django 6.0.4 on 2026-04-29 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('products', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INC', 'Увеличение'), ('DEC', 'Уменьшение'), ('SET', 'Установка значения')], max_length=3, verbose_name='Тип корректировки')),
                ('quantity', models.IntegerField(help_text='Количество для увеличения/уменьшения или новое значение при установке', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('reason', models.TextField(help_text='Обязательно укажите причину корректировки остатков', max_length=500, verbose_name='Причина корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата корректировки')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные примечания')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Кто выполнил корректировку')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Корректировка инвентаря',
                'verbose_name_plural': 'Корректировки инвентаря',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количство на складе')),
                ('last_received_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего прибавления')),
                ('last_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего убавления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Buy', 'В плюс'), ('Sell', 'В минус')], max_length=10)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('data', models.DateField(auto_now_add=True)),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Примечание')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='accounting.contract', verbose_name='Контракт')),
                ('sold_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Лог Движений на складе',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='Название автомобиля')),
                ('plate_number', models.CharField(max_length=6, null=True, verbose_name='Номерной знак')),
                ('milage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('year', models.DateField(verbose_name='Год выпуска')),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Гараж',
                'unique_together': {('milage', 'vehicle_name')},
            },
        ),
    ]
