# Generated by Django 5.1.6 on 2025-04-10 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0013_alter_financialtransactions_source_and_more'),
        ('products', '0004_alter_product_type_product'),
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количство на складе')),
                ('last_received_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего прибавления')),
                ('last_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего убавления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Buy', 'В плюс'), ('Sell', 'В минус')], max_length=10)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('data', models.DateField(auto_now_add=True)),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Примечание')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='accounting.contract', verbose_name='Контракт')),
                ('sold_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_product', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Лог Движений на складе',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='Название автомобиля')),
                ('plate_number', models.CharField(max_length=6, null=True, verbose_name='Номерной знак')),
                ('milage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('year', models.DateField(verbose_name='Год выпуска')),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Гараж',
                'unique_together': {('milage', 'vehicle_name')},
            },
        ),
    ]
