# Generated by Django 5.1.6 on 2025-04-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_contract_client_alter_installment_client_and_more'),
        ('products', '0004_alter_product_type_product'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='accounting.contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='sold_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='products.product', verbose_name='Продукт'),
        ),
    ]
