# Generated by Django 5.1.6 on 2026-08-20 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type_product'),
        ('warehouse', '0001_initial'),
        ('workers', '0007_remove_dispatcher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Складской продукт',
                'verbose_name_plural': 'Складские продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INC', 'Увеличение'), ('DEC', 'Уменьшение'), ('SET', 'Установка значения')], max_length=3, verbose_name='Тип корректировки')),
                ('quantity', models.IntegerField(help_text='Количество для увеличения/уменьшения или новое значение при установке', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('reason', models.TextField(help_text='Обязательно укажите причину корректировки остатков', max_length=500, verbose_name='Причина корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата корректировки')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительные примечания')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Кто выполнил корректировку')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='warehouse.warehouseproduct', verbose_name='Складской продукт')),
            ],
            options={
                'verbose_name': 'Корректировка складского продукта',
                'verbose_name_plural': 'Корректировки складских продуктов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('last_received_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний приход')),
                ('last_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний расход')),
                ('warehouse_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='warehouse.warehouseproduct', verbose_name='Складской продукт')),
            ],
            options={
                'verbose_name': 'Остаток складского продукта',
                'verbose_name_plural': 'Остатки складских продуктов',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.warehouseproduct', verbose_name='Складской продукт')),
            ],
            options={
                'verbose_name': 'Движение складского продукта',
                'verbose_name_plural': 'Движения складских продуктов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Сколько единиц складского продукта списывается за 1 проданный продукт', verbose_name='Коэффициент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_mappings', to='products.product', verbose_name='Продукт ассортимента')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='warehouse.warehouseproduct', verbose_name='Складской продукт')),
            ],
            options={
                'verbose_name': 'Связь продукта со складом',
                'verbose_name_plural': 'Связи продуктов со складом',
                'unique_together': {('product', 'warehouse_product')},
            },
        ),
    ]
