# Generated by Django 5.1.6 on 2026-04-27 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_track_inventory'),
        ('warehouse', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INC', 'Увеличение'), ('DEC', 'Уменьшение'), ('SET', 'Установка значения')], max_length=3, verbose_name='Тип корректировки')),
                ('quantity', models.IntegerField(help_text='Количество для увеличения/уменьшения или новое значение при установке', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('reason', models.TextField(help_text='Обязательно укажите причину корректировки остатков', max_length=500, verbose_name='Причина корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата корректировки')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные примечания')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Кто выполнил корректировку')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Корректировка инвентаря',
                'verbose_name_plural': 'Корректировки инвентаря',
                'ordering': ['-created_at'],
            },
        ),
    ]
