# Generated by Django 5.1.6 on 2025-03-11 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='quantitly',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количство на складе'),
        ),
    ]
