# Generated by Django 5.1.6 on 2026-08-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouseproduct_warehouseinventoryadjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbalance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='sold_product',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustment',
        ),
        migrations.DeleteModel(
            name='StockBalance',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
