# Generated by Django 5.1.6 on 2025-03-13 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
        ('warehouse', '0002_alter_stockbalance_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('By', 'В плюс'), ('Sell', 'В минус')], max_length=10)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('data', models.DateField(auto_now_add=True)),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Примечание')),
                ('sold_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_product', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Движения на складе',
            },
        ),
    ]
