# Generated by Django 5.1.6 on 2026-08-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_stockbalance_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
