# Generated by Django 5.1.6 on 2025-03-13 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_stockmovement'),
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Лог Движений на складе'},
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='Название автомобиля')),
                ('milage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2015)], verbose_name='Год')),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гаражи',
                'unique_together': {('milage', 'vehicle_name')},
            },
        ),
    ]
