# Generated by Django 5.1.6 on 2026-08-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_garage_options'),
        ('workers', '0009_alter_worker_created_at_alter_worker_date_for_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='courier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Курьер'),
        ),
    ]
