# Generated by Django 5.1.6 on 2025-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_stockmovement_options_garage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Гараж'},
        ),
    ]
