# Generated by Django 5.1.6 on 2026-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_garage_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='plate_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номерной знак'),
        ),
    ]
