# Generated by Django 5.1.6 on 2025-03-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_finance_financialtransactions_subjectcontract'),
        ('warehouse', '0005_alter_garage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='plate_number',
            field=models.CharField(max_length=6, null=True, verbose_name='Номерной знак'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='accounting.contract', verbose_name='Контракт'),
        ),
    ]
