# Generated by Django 5.1.6 on 2025-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_garage_plate_number_stockmovement_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='operation_type',
            field=models.CharField(choices=[('Buy', 'В плюс'), ('Sell', 'В минус')], max_length=10),
        ),
    ]
