# Generated by Django 5.1.6 on 2025-03-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_stockmovement_operation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbalance',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
