# Generated by Django 5.1.6 on 2025-03-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_rename_quantity_stockbalance_quantitly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbalance',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
