# Generated by Django 5.1.6 on 2025-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_rename_quantity_stockbalance_quantitly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='last_departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего убавления'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='last_received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего прибавления'),
        ),
    ]
