# Generated by Django 5.1.6 on 2025-03-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TK', 'Взято'), ('BG', 'Принесено'), ('RT', 'Возврат')], max_length=2, verbose_name='Тип действия')),
                ('quantity', models.IntegerField(verbose_name='Количевство')),
                ('date', models.DateField(auto_now_add=True)),
                ('courier_name', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='couriers', to='workers.worker', verbose_name='Курьер')),
            ],
        ),
    ]
