# Generated by Django 6.0.4 on 2026-04-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата смены')),
                ('status', models.CharField(choices=[('OP', 'Открыта'), ('CL', 'Закрыта')], default='OP', max_length=2)),
                ('cash_total', models.IntegerField(default=0, verbose_name='Наличные за смену')),
                ('card_total', models.IntegerField(default=0, verbose_name='Безнал за смену')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Смена курьера',
                'verbose_name_plural': 'Смены курьеров',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourierTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_loaded', models.IntegerField(verbose_name='Загружено полных баклажек')),
                ('full_returned', models.IntegerField(default=0, verbose_name='Возвращено полных (недоставленных)')),
                ('status', models.CharField(choices=[('AC', 'В пути'), ('DN', 'Завершён')], default='AC', max_length=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logistics.couriershift')),
            ],
            options={
                'verbose_name': 'Рейс курьера',
                'verbose_name_plural': 'Рейсы курьеров',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('card_price', models.IntegerField(default=0, verbose_name='Сумма картой')),
                ('total_price', models.IntegerField(default=0, verbose_name='Сумма налом')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Журнал доставок',
                'verbose_name_plural': 'Журналы доставок',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryJournalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('payment_type', models.CharField(choices=[('CD', 'Карта'), ('CH', 'Наличные'), ('BS', 'Бонус')], default='CH', max_length=2, verbose_name='Тип оплаты')),
                ('delivery_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.deliveryjournal', verbose_name='Журнал доставки')),
                ('product', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в журнале доставок',
                'verbose_name_plural': 'Продукты в журналах доставок',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(blank=True, help_text='Кол-во проданой воды с тарой или несоответсвие, пропажа', null=True, verbose_name='Количевство')),
                ('total_sold', models.IntegerField(blank=True, null=True, verbose_name='Всего проданно:')),
                ('date', models.DateField(verbose_name='Дата')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Журнал учета тар',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLogMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TK', 'Взято'), ('BG', 'Принесено'), ('RT', 'Возврат')], max_length=2, verbose_name='Тип действия')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата дейсвия')),
                ('delivery_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.deliverylog', verbose_name='Журнал')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('BS', 'Бонус')], default='CH', max_length=2)),
                ('status', models.CharField(choices=[('PD', 'Ожидает'), ('DL', 'Доставлен'), ('CN', 'Отменён')], default='PD', max_length=2)),
                ('container_op', models.CharField(blank=True, choices=[('EX', 'Обмен (пустая → полная)'), ('SW', 'Продажа с тарой'), ('DF', 'Возврат брака')], help_text='Заполняется курьером при подтверждении доставки', max_length=2, null=True, verbose_name='Операция с тарой')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='logistics.couriertrip')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
