# Generated by Django 5.1.6 on 2025-03-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylog',
            options={'verbose_name': 'Журнал учета тар'},
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Описание')),
                ('payment', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bonus', 'Бонус')], max_length=10, verbose_name='Тип оплаты')),
                ('summary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма стоимости')),
                ('accessory', models.ForeignKey(blank=True, limit_choices_to={'type_product': 'accessory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='products.product', verbose_name='Аксессуар')),
                ('bottle', models.ForeignKey(blank=True, limit_choices_to={'type_product': 'bottle'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='products.product', verbose_name='Бутыль')),
                ('cooler', models.ForeignKey(blank=True, limit_choices_to={'type_product': 'cooler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coolers', to='products.product', verbose_name='Кулер')),
                ('water', models.ForeignKey(blank=True, limit_choices_to={'type_product': 'water'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waters', to='products.product', verbose_name='Вода')),
            ],
        ),
    ]
