# Generated by Django 5.1.6 on 2026-05-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('workers', '0002_worker_is_admin_worker_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryjournal',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='card_price',
        ),
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='workers.worker', verbose_name='Назначенный курьер'),
        ),
        migrations.DeleteModel(
            name='DeliveryJournalProducts',
        ),
    ]
