# Generated by Django 5.1.6 on 2025-03-14 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_deliverylog_options_deliveryreport'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='accessory',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_product': 'AR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='products.product'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='bottle',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_product': 'B20L'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='products.product'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='cooler',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_product': 'CL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coolers', to='products.product'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='note',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='payment',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('bonus', 'Бонус')], max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='water',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_product': 'WE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waters', to='products.product'),
        ),
    ]
