# Generated by Django 5.1.6 on 2025-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_deliveryreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
