# Generated by Django 5.1.6 on 2025-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_deliveryreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='accessory_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество аксессуаров'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='bottle_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бутылей'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='cooler_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество кулеров'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='water_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество воды'),
        ),
    ]
