# Generated by Django 5.1.6 on 2026-07-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_order_container_op_remove_order_price_and_more'),
        ('workers', '0003_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='workers.worker', verbose_name='Создал заказ'),
        ),
    ]
