# Generated by Django 5.1.6 on 2026-07-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_address'),
        ('logistics', '0005_order_created_by_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.clientaddress', verbose_name='Адрес доставки'),
        ),
    ]
