# Generated by Django 5.1.6 on 2025-03-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_deliveryreport_accessory_quantity_and_more'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='accessory_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='bottle',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='bottle_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='cooler',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='cooler_quantity',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='water',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='water_quantity',
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.CreateModel(
            name='DeliveryReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.deliveryreport', verbose_name='Отчет')),
            ],
        ),
    ]
