# Generated by Django 5.1.6 on 2025-03-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_deliveryreport_accessory_and_more'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreportitem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='deliveryreportitem',
            name='product',
        ),
        migrations.CreateModel(
            name='DeliveryJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('note', models.TextField(verbose_name='Описание')),
                ('total_price', models.IntegerField(default=0, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('CD', 'Карта'), ('CH', 'Наличные'), ('BS', 'Бонус')], default='CH', verbose_name='Тип оплаты')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workers.worker', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Журнал доставок',
                'verbose_name_plural': 'Журналы доставок',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryJournalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('delivery_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.deliveryjournal', verbose_name='Журнал доставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в журнале доставок',
                'verbose_name_plural': 'Продукты в журналах доставок',
            },
        ),
        migrations.DeleteModel(
            name='DeliveryReport',
        ),
        migrations.DeleteModel(
            name='DeliveryReportItem',
        ),
    ]
