# Generated by Django 5.1.6 on 2026-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_order_delivery_address_text_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveSmallIntegerField(default=0, verbose_name='Текущий номер')),
            ],
            options={
                'verbose_name': 'Счетчик номеров заказов',
                'verbose_name_plural': 'Счетчик номеров заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='display_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Декоративный номер'),
        ),
    ]
