# Generated by Django 5.1.6 on 2025-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_deliveryreportitem_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='note',
        ),
        migrations.AddField(
            model_name='deliveryjournalproducts',
            name='note',
            field=models.TextField(default='dd', verbose_name='Описание'),
        ),
    ]
