# Generated by Django 5.1.6 on 2025-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_deliveryjournal_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='note',
            field=models.CharField(verbose_name='Описание'),
        ),
    ]
