# Generated by Django 5.1.6 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_order_display_number_and_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylog',
            options={'verbose_name': 'Журнал учёта тары', 'verbose_name_plural': 'Журналы учёта тары'},
        ),
        migrations.AlterModelOptions(
            name='deliverylogmove',
            options={'verbose_name': 'Движение журнала', 'verbose_name_plural': 'Движения журнала'},
        ),
        migrations.AlterField(
            model_name='deliverylogmove',
            name='date',
            field=models.DateField(verbose_name='Дата действия'),
        ),
    ]
