# Generated by Django 5.1.6 on 2026-08-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_deliverylog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLog',
        ),
        migrations.DeleteModel(
            name='DeliveryLogMove',
        ),
    ]
