# Generated by Django 5.1.6 on 2025-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_deliveryjournalproducts_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='note',
            field=models.CharField(null=True, verbose_name='Описание'),
        ),
    ]
