# Generated by Django 5.1.6 on 2026-08-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_legacy_models'),
        ('workers', '0009_alter_worker_created_at_alter_worker_date_for_payed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryJournal',
        ),
        migrations.AlterField(
            model_name='couriershift',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Курьер'),
        ),
    ]
