# Generated by Django 5.1.6 on 2025-03-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_deliveryjournalproducts_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylog',
            old_name='courier_name',
            new_name='courier',
        ),
        migrations.RemoveField(
            model_name='deliverylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='deliverylog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='total_quantity',
            field=models.IntegerField(blank=True, help_text='Кол-во проданой воды с тарой или несоответсвие, пропажа', null=True, verbose_name='Количевство'),
        ),
        migrations.CreateModel(
            name='DeliveryLogMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TK', 'Взято'), ('BG', 'Принесено'), ('RT', 'Возврат')], verbose_name='Тип действия')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата дейсвия')),
                ('delivery_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.deliverylog', verbose_name='Журнал')),
            ],
        ),
    ]
