# Generated by Django 5.1.6 on 2025-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_rename_courier_name_deliverylog_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='deliveryjournalproducts',
            name='payment_type',
            field=models.CharField(choices=[('CD', 'Карта'), ('CH', 'Наличные'), ('BS', 'Бонус')], default='CH', verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='deliveryjournalproducts',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
