# Generated by Django 5.1.6 on 2025-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_remove_deliveryjournal_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournal',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
