# Generated by Django 5.1.6 on 2025-03-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_deliveryjournal_date'),
        ('products', '0003_remove_product_quantitly_alter_product_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Продукт'),
        ),
    ]
