# Generated by Django 5.1.6 on 2025-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_deliveryjournalproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='note',
            field=models.CharField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
