# Generated by Django 5.1.6 on 2025-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_deliveryjournalproducts_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjournal',
            name='card_price',
            field=models.IntegerField(default=0, verbose_name='Сумма картой'),
        ),
        migrations.AddField(
            model_name='deliveryjournal',
            name='cash_price',
            field=models.IntegerField(default=0, verbose_name='Сумма налом'),
        ),
        migrations.AlterField(
            model_name='deliveryjournal',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
