# Generated by Django 5.1.6 on 2025-03-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_deliveryjournal_card_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryjournal',
            name='cash_price',
        ),
    ]
