# Generated by Django 5.1.6 on 2025-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_remove_deliveryjournal_cash_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='total_sold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего проданно:'),
        ),
    ]
