# Generated by Django 5.1.6 on 2025-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_deliverylog_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylog',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
