# Generated by Django 5.1.6 on 2025-03-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_alter_deliverylog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylogmove',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
