# Generated by Django 5.1.6 on 2025-03-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_rename_quantity_deliverylogmove_quantitly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylogmove',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
