# Generated by Django 5.1.6 on 2025-04-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_rename_quantity_deliverylogmove_quantitly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylogmove',
            old_name='quantitly',
            new_name='quantity',
        ),
    ]
