# Generated by Django 5.1.6 on 2025-04-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_rename_quantitly_deliverylogmove_quantity'),
        ('products', '0004_alter_product_type_product'),
        ('workers', '0002_worker_date_for_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournal',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='workers.worker', verbose_name='Курьер'),
        ),
    ]
