# Generated by Django 5.1.6 on 2026-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_alter_deliveryjournal_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryjournal',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Сумма налом'),
        ),
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deliveryjournalproducts',
            name='payment_type',
            field=models.CharField(choices=[('CD', 'Карта'), ('CH', 'Наличные'), ('BS', 'Бонус')], default='CH', max_length=2, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='deliverylogmove',
            name='action',
            field=models.CharField(choices=[('TK', 'Взято'), ('BG', 'Принесено'), ('RT', 'Возврат')], max_length=2, verbose_name='Тип действия'),
        ),
    ]
