# Generated by Django 5.1.6 on 2026-04-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('worker_type', models.CharField(choices=[('packer', 'Упаковщик'), ('courier', 'Курьер'), ('other', 'Прочие')], max_length=10, verbose_name='Тип сотрудника')),
                ('date_for_payed', models.DateField(blank=True, default=datetime.date.today, verbose_name='Начисление зарплаты')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Созданно')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обнавлено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
