# Generated by Django 5.1.6 on 2025-03-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_for_payed',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Начисление зарплаты'),
        ),
    ]
