# Generated by Django 5.1.6 on 2026-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Даёт доступ к командам администратора в Telegram-боте', verbose_name='Администратор бота'),
        ),
        migrations.AddField(
            model_name='worker',
            name='tg_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram для авторизации в боте', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
