# Generated by Django 5.1.6 on 2026-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_is_admin_worker_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона сотрудника', max_length=20, verbose_name='Телефон'),
        ),
    ]
