# Generated by Django 5.1.6 on 2026-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('packer', 'Упаковщик'), ('courier', 'Курьер'), ('operator', 'Оператор'), ('other', 'Прочие')], max_length=10, verbose_name='Тип сотрудника'),
        ),
    ]
