# Generated by Django 5.1.6 on 2026-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_worker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('packer', 'Упаковщик'), ('courier', 'Курьер'), ('operator', 'Оператор'), ('owner', 'Владелец'), ('other', 'Прочие')], max_length=10, verbose_name='Тип сотрудника'),
        ),
    ]
