# Generated by Django 5.1.6 on 2026-08-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_remove_dispatcher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary_amount',
            field=models.IntegerField(default=0, help_text='Фиксированный месячный оклад сотрудника. Используется при авто-начислении зарплаты.', verbose_name='Оклад (сум)'),
        ),
    ]
