# Generated by Django 5.1.6 on 2026-08-23 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_worker_salary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_for_payed',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата начисления зарплаты'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
