# Generated by Django 5.1.6 on 2025-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, verbose_name='ФИО')),
                ('phone', models.IntegerField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=120, verbose_name='Адрес')),
                ('balans', models.IntegerField(max_length=6, null=True, verbose_name='Предоплата')),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования')),
            ],
        ),
    ]
