# Generated by Django 6.0.4 on 2026-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('balans', models.IntegerField(blank=True, null=True, verbose_name='Предоплата')),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Примечание')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования')),
            ],
        ),
    ]
