# Generated by Django 5.1.6 on 2026-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Номер телефона'),
        ),
    ]
