# Generated by Django 5.1.6 on 2026-07-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
