# Generated by Django 5.1.6 on 2025-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balans',
            field=models.IntegerField(null=True, verbose_name='Предоплата'),
        ),
    ]
