# Generated by Django 5.1.6 on 2025-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_adress_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предоплата'),
        ),
    ]
