# Generated by Django 5.1.6 on 2026-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options_clientaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Адрес (устарело, используйте ClientAddress)'),
        ),
    ]
