# Generated by Django 5.1.6 on 2026-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Метка (Дом, Офис, Работа)'),
        ),
    ]
