# Generated by Django 5.1.6 on 2026-08-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientaddress_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
